# Generated by Django 4.2.6 on 2023-10-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_words', models.CharField(max_length=128, unique=True)),
                ('ru_words', models.CharField(max_length=128)),
            ],
        ),
    ]
